kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterpool-postinstall-import-claimed-cluster-role
rules:
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - list
      - get
      - patch
      - create
  - apiGroups:
      - hive.openshift.io
    resources:
      - clusterclaims
    verbs:
      - list
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - patch
      - get
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclustersets
    verbs:
      - list
      - get
      - patch
      - create
