kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterpool-postinstall-import-claimed-cluster-role
rules:
  - apiGroups:
      - cluster.open-cluster-management.io
    resources:
      - managedclusters
    verbs:
      - list
